(defpackage :test-geometry (:use :common-lisp :2d-geometry :vecto))

(in-package :test-geometry)

(defun test-triangulate (polygon)
  (with-canvas (:width 400 :height 400)
    (set-rgb-fill 0 0 200)
    (move-to (x (car polygon))(y (car polygon)))
    (dolist (tk polygon)
      (line-to (x tk)(y tk)))
    (line-to (x (car polygon))(y (car polygon)))
    (fill-path)
    (set-rgb-stroke 0 255 0)
    (set-line-width 1/15)
    (set-line-join :bevel)
    (dolist (tk (triangulate *poly*))
      (move-to (x (car tk))(y (car tk)))
      (dolist (kk tk)
	(line-to (x kk)(y kk)))
      (line-to (x (car tk))(y (car tk))))
    (stroke)
    (save-png "test-geometry.png")))